In [1]:
#project 2
import pandas as pd
from pathlib import Path
import numpy as np

In [2]:
#Read CSV
Path="Resources/Zip_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_mon.csv"
price_df= pd.read_csv(Path)
price_df.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,1996-01-31,...,2020-05-31,2020-06-30,2020-07-31,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31,2021-01-31,2021-02-28
0,61639,0,10025,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,232527.0,...,1124579.0,1119261.0,1114733.0,1112570.0,1113554.0,1108906.0,1104331.0,1098915.0,1089614.0,1090168.0
1,84654,1,60657,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,208780.0,...,488778.0,489319.0,490664.0,492714.0,495483.0,498200.0,500780.0,503294.0,505577.0,508007.0
2,61637,2,10023,Zip,NY,NY,New York,New York-Newark-Jersey City,New York County,184917.0,...,913735.0,916274.0,916593.0,920113.0,931353.0,934916.0,934687.0,930893.0,934775.0,945772.0
3,91982,3,77494,Zip,TX,TX,Katy,Houston-The Woodlands-Sugar Land,Harris County,199929.0,...,336901.0,337728.0,338452.0,339876.0,341435.0,343897.0,346910.0,351188.0,355336.0,360190.0
4,84616,4,60614,Zip,IL,IL,Chicago,Chicago-Naperville-Elgin,Cook County,281068.0,...,629766.0,629807.0,630985.0,632529.0,635442.0,638288.0,641416.0,644506.0,647307.0,650905.0

In [3]:
#Filter dataframe
price_df=price_df.drop(columns=["RegionID","SizeRank","RegionName","RegionType","StateName"]).copy()
price_df

,State,City,Metro,CountyName,1996-01-31,1996-02-29,1996-03-31,1996-04-30,1996-05-31,1996-06-30,...,2020-05-31,2020-06-30,2020-07-31,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31,2021-01-31,2021-02-28
0,NY,New York,New York-Newark-Jersey City,New York County,232527.0,231079.0,231156.0,231131.0,231660.0,232303.0,...,1124579.0,1119261.0,1114733.0,1112570.0,1113554.0,1108906.0,1104331.0,1098915.0,1089614.0,1090168.0
1,IL,Chicago,Chicago-Naperville-Elgin,Cook County,208780.0,208625.0,208220.0,208086.0,207527.0,207709.0,...,488778.0,489319.0,490664.0,492714.0,495483.0,498200.0,500780.0,503294.0,505577.0,508007.0
2,NY,New York,New York-Newark-Jersey City,New York County,184917.0,184955.0,185058.0,185717.0,186675.0,187460.0,...,913735.0,916274.0,916593.0,920113.0,931353.0,934916.0,934687.0,930893.0,934775.0,945772.0
3,TX,Katy,Houston-The Woodlands-Sugar Land,Harris County,199929.0,200176.0,199980.0,198794.0,197659.0,196995.0,...,336901.0,337728.0,338452.0,339876.0,341435.0,343897.0,346910.0,351188.0,355336.0,360190.0
4,IL,Chicago,Chicago-Naperville-Elgin,Cook County,281068.0,280811.0,280293.0,280152.0,279477.0,279565.0,...,629766.0,629807.0,630985.0,632529.0,635442.0,638288.0,641416.0,644506.0,647307.0,650905.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30338,OR,Central Point,Medford,Jackson County,NaN,NaN,NaN,NaN,NaN,NaN,...,147808.0,149015.0,149286.0,149493.0,149872.0,151352.0,152961.0,156051.0,160039.0,164643.0
30339,TX,Texarkana,Texarkana,Bowie County,NaN,NaN,NaN,NaN,NaN,NaN,...,49084.0,48557.0,48263.0,48361.0,48416.0,48625.0,49064.0,49603.0,50003.0,50320.0
30340,MA,Groton,Boston-Cambridge-Newton,Middlesex County,NaN,NaN,NaN,NaN,NaN,NaN,...,387810.0,387823.0,387806.0,388207.0,389813.0,391532.0,393895.0,393194.0,392171.0,393842.0
30341,LA,Choudrant,Ruston,Lincoln Parish,NaN,NaN,NaN,NaN,NaN,NaN,...,200140.0,199806.0,199449.0,199659.0,199228.0,198112.0,196824.0,196220.0,195117.0,192702.0
30342,UT,Charlotte Amalie,NaN,Kane County,NaN,NaN,NaN,NaN,NaN,NaN,...,34540.0,34565.0,34599.0,34644.0,34698.0,34715.0,34795.0,34882.0,35035.0,35138.0

In [4]:
#extract only Bay Area Counties
bayarea_price_df = price_df[price_df["CountyName"].isin(["San Francisco County","San Mateo County","Santa Clara County","Alameda County","Contra Costa County","Marin County"])].dropna()
bayarea_price_df

,State,City,Metro,CountyName,1996-01-31,1996-02-29,1996-03-31,1996-04-30,1996-05-31,1996-06-30,...,2020-05-31,2020-06-30,2020-07-31,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31,2021-01-31,2021-02-28
13,CA,San Francisco,San Francisco-Oakland-Hayward,San Francisco County,333727.0,332205.0,331788.0,330713.0,330535.0,330277.0,...,1217984.0,1210221.0,1204887.0,1201422.0,1198273.0,1185486.0,1174127.0,1158873.0,1147199.0,1132611.0
86,CA,Alameda,San Francisco-Oakland-Hayward,Alameda County,183651.0,182684.0,182409.0,181685.0,181500.0,180861.0,...,1076034.0,1075570.0,1077038.0,1086790.0,1097824.0,1113689.0,1128931.0,1140118.0,1146929.0,1159571.0
92,CA,San Francisco,San Francisco-Oakland-Hayward,San Francisco County,285314.0,283786.0,282878.0,281548.0,280920.0,280286.0,...,1613069.0,1604729.0,1598217.0,1598760.0,1598630.0,1584055.0,1571072.0,1557327.0,1551159.0,1540788.0
227,CA,Fremont,San Francisco-Oakland-Hayward,Alameda County,202048.0,201616.0,201610.0,201552.0,201948.0,202098.0,...,1064742.0,1064136.0,1069105.0,1082096.0,1095959.0,1112354.0,1129735.0,1144798.0,1155304.0,1169765.0
270,CA,San Jose,San Jose-Sunnyvale-Santa Clara,Santa Clara County,199719.0,199149.0,198988.0,198670.0,198752.0,198886.0,...,989819.0,990213.0,993742.0,1008738.0,1019813.0,1033190.0,1043574.0,1054422.0,1059563.0,1061644.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25187,CA,San Quentin,San Francisco-Oakland-Hayward,Marin County,660013.0,655020.0,653387.0,650170.0,648756.0,650596.0,...,1205480.0,1189553.0,1178215.0,1172621.0,1157268.0,1135241.0,1114668.0,1106883.0,1105517.0,1093936.0
25789,CA,Tomales,San Francisco-Oakland-Hayward,Marin County,361426.0,361838.0,363166.0,365012.0,367697.0,371855.0,...,851142.0,855248.0,862179.0,878421.0,894595.0,913852.0,925617.0,937562.0,948524.0,950917.0
26545,CA,Dillon Beach,San Francisco-Oakland-Hayward,Marin County,425738.0,423289.0,424159.0,422953.0,425435.0,424763.0,...,943496.0,940175.0,942274.0,959321.0,971260.0,983792.0,992155.0,1011505.0,1034734.0,1057952.0
26799,CA,East Foothills,San Jose-Sunnyvale-Santa Clara,Santa Clara County,306188.0,305729.0,307095.0,308975.0,310864.0,310383.0,...,1501630.0,1500622.0,1511586.0,1535741.0,1551543.0,1562483.0,1576453.0,1601002.0,1625908.0,1646494.0
30200,CA,San Jose,San Jose-Sunnyvale-Santa Clara,Santa Clara County,731728.0,727459.0,722102.0,713873.0,703637.0,693762.0,...,1564470.0,1579773.0,1584684.0,1590669.0,1611499.0,1646078.0,1684580.0,1702669.0,1722140.0,1737608.0

In [5]:
#merge rows based on cities and average the prices
bayarea_price_df = bayarea_price_df.groupby("City").mean()
# bayarea_price_df.head(10)
bayarea_price_df.tail(10)

,1996-01-31,1996-02-29,1996-03-31,1996-04-30,1996-05-31,1996-06-30,1996-07-31,1996-08-31,1996-09-30,1996-10-31,...,2020-05-31,2020-06-30,2020-07-31,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31,2021-01-31,2021-02-28
City,,,,,,,,,,,,,,,,,,,,,
Sausalito,418281.0,418168.000000,417992.000000,416866.0,415518.000000,415244.000000,416296.000000,418231.000000,419864.0,422071.000000,...,1.427186e+06,1.435426e+06,1.454300e+06,1.474565e+06,1493884.0,1.504451e+06,1.510044e+06,1.513988e+06,1.517103e+06,1512237.0
South San Francisco,246054.0,245417.000000,245088.000000,244511.0,244330.000000,244320.000000,244137.000000,244141.000000,244332.0,245037.000000,...,1.109258e+06,1.104639e+06,1.105953e+06,1.114798e+06,1117698.0,1.126120e+06,1.131496e+06,1.140527e+06,1.142975e+06,1145123.0
Stanford,889953.0,887237.000000,885073.000000,880249.0,877671.000000,877668.000000,880005.000000,882395.000000,885890.0,895623.000000,...,3.322582e+06,3.321162e+06,3.329739e+06,3.352401e+06,3353488.0,3.340200e+06,3.313555e+06,3.299328e+06,3.296527e+06,3293454.0
Sunnyvale,280969.5,280449.750000,280286.000000,280173.5,280281.000000,280720.000000,281136.000000,282073.000000,283058.5,284779.500000,...,1.523418e+06,1.527867e+06,1.540020e+06,1.566819e+06,1583589.5,1.600358e+06,1.608220e+06,1.619694e+06,1.624199e+06,1626406.5
Sunol,225325.0,225673.000000,225943.000000,227042.0,228308.000000,229935.000000,231743.000000,234449.000000,236917.0,239859.000000,...,1.245185e+06,1.230376e+06,1.229016e+06,1.239155e+06,1248554.0,1.256977e+06,1.261966e+06,1.269181e+06,1.266187e+06,1271260.0
Tiburon,637431.0,632332.000000,628498.000000,621511.0,616985.000000,613715.000000,610722.000000,609420.000000,608861.0,611261.000000,...,2.911483e+06,2.936307e+06,2.966113e+06,3.008070e+06,3037545.0,3.063225e+06,3.070614e+06,3.081271e+06,3.093201e+06,3092271.0
Tomales,361426.0,361838.000000,363166.000000,365012.0,367697.000000,371855.000000,375624.000000,375387.000000,371345.0,368291.000000,...,8.511420e+05,8.552480e+05,8.621790e+05,8.784210e+05,894595.0,9.138520e+05,9.256170e+05,9.375620e+05,9.485240e+05,950917.0
Union City,200579.0,199914.000000,199690.000000,199190.0,199051.000000,198737.000000,198392.000000,198337.000000,198617.0,199434.000000,...,9.207270e+05,9.207450e+05,9.263200e+05,9.388170e+05,952768.0,9.690100e+05,9.856330e+05,9.993660e+05,1.008695e+06,1021168.0
Walnut Creek,176408.0,175915.333333,175676.333333,174950.0,174947.666667,174924.333333,175796.333333,176614.666667,177540.0,178469.666667,...,6.755723e+05,6.768227e+05,6.797997e+05,6.889003e+05,698423.0,7.060303e+05,7.107367e+05,7.143537e+05,7.213223e+05,728791.0
Woodacre,351023.0,346049.000000,343912.000000,340124.0,339538.000000,340910.000000,340496.000000,340995.000000,339745.0,340996.000000,...,8.886960e+05,8.939550e+05,9.051950e+05,9.205120e+05,933940.0,9.508100e+05,9.597210e+05,9.690280e+05,9.729460e+05,977544.0

In [6]:
transposed_bayarea_price_df = bayarea_price_df.transpose()
transposed_bayarea_price_df

City,Alameda,Alamo,Albany,Antioch,Atherton,Belmont,Berkeley,Bethel Island,Brentwood,Brisbane,...,Sausalito,South San Francisco,Stanford,Sunnyvale,Sunol,Tiburon,Tomales,Union City,Walnut Creek,Woodacre
1996-01-31,205976.5,519268.0,215162.0,135345.5,768920.0,382693.0,230439.500,91301.0,177652.0,228102.0,...,418281.0,246054.0,889953.0,280969.50,225325.0,637431.0,361426.0,200579.0,176408.000000,351023.0
1996-02-29,205057.0,515543.0,213857.0,134862.5,768438.0,381255.0,230150.500,90636.0,176822.0,227429.0,...,418168.0,245417.0,887237.0,280449.75,225673.0,632332.0,361838.0,199914.0,175915.333333,346049.0
1996-03-31,204658.5,512075.0,212882.0,134612.0,768815.0,380609.0,229926.875,90535.0,176728.0,227101.0,...,417992.0,245088.0,885073.0,280286.00,225943.0,628498.0,363166.0,199690.0,175676.333333,343912.0
1996-04-30,203799.0,504934.0,211755.0,134150.0,768997.0,379324.0,229266.875,90237.0,175787.0,225730.0,...,416866.0,244511.0,880249.0,280173.50,227042.0,621511.0,365012.0,199190.0,174950.000000,340124.0
1996-05-31,203365.0,495856.0,211241.0,133767.0,770878.0,378795.0,228541.500,90535.0,175004.0,224809.0,...,415518.0,244330.0,877671.0,280281.00,228308.0,616985.0,367697.0,199051.0,174947.666667,339538.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-10-31,1077678.5,1996807.0,1161087.0,500070.5,6559876.0,1881854.0,1441616.125,480198.0,711031.0,1089723.0,...,1504451.0,1126120.0,3340200.0,1600357.75,1256977.0,3063225.0,913852.0,969010.0,706030.333333,950810.0
2020-11-30,1089846.0,2022829.0,1174722.0,503803.0,6548970.0,1894115.0,1456860.250,489826.0,718918.0,1097467.0,...,1510044.0,1131496.0,3313555.0,1608220.25,1261966.0,3070614.0,925617.0,985633.0,710736.666667,959721.0
2020-12-31,1098396.5,2044018.0,1184064.0,507494.0,6586869.0,1913411.0,1469732.250,500088.0,726098.0,1109885.0,...,1513988.0,1140527.0,3299328.0,1619693.50,1269181.0,3081271.0,937562.0,999366.0,714353.666667,969028.0
2021-01-31,1104088.0,2077690.0,1189380.0,514168.0,6557351.0,1921137.0,1480483.875,511506.0,737794.0,1116322.0,...,1517103.0,1142975.0,3296527.0,1624199.00,1266187.0,3093201.0,948524.0,1008695.0,721322.333333,972946.0
2021-02-28,1114772.5,2112884.0,1201063.0,522110.0,6542985.0,1930446.0,1497262.500,523415.0,751040.0,1120078.0,...,1512237.0,1145123.0,3293454.0,1626406.50,1271260.0,3092271.0,950917.0,1021168.0,728791.000000,977544.0

In [7]:
#percent change of each year
yoy_percent_change=transposed_bayarea_price_df.pct_change().dropna()
yoy_percent_change

City,Alameda,Alamo,Albany,Antioch,Atherton,Belmont,Berkeley,Bethel Island,Brentwood,Brisbane,...,Sausalito,South San Francisco,Stanford,Sunnyvale,Sunol,Tiburon,Tomales,Union City,Walnut Creek,Woodacre
1996-02-29,-0.004464,-0.007174,-0.006065,-0.003569,-0.000627,-0.003758,-0.001254,-0.007284,-0.004672,-0.002950,...,-0.000270,-0.002589,-0.003052,-0.001850,0.001544,-0.007999,0.001140,-0.003315,-0.002793,-0.014170
1996-03-31,-0.001943,-0.006727,-0.004559,-0.001857,0.000491,-0.001694,-0.000972,-0.001114,-0.000532,-0.001442,...,-0.000421,-0.001341,-0.002439,-0.000584,0.001196,-0.006063,0.003670,-0.001120,-0.001359,-0.006175
1996-04-30,-0.004200,-0.013945,-0.005294,-0.003432,0.000237,-0.003376,-0.002870,-0.003292,-0.005325,-0.006037,...,-0.002694,-0.002354,-0.005450,-0.000401,0.004864,-0.011117,0.005083,-0.002504,-0.004134,-0.011014
1996-05-31,-0.002130,-0.017979,-0.002427,-0.002855,0.002446,-0.001395,-0.003164,0.003302,-0.004454,-0.004080,...,-0.003234,-0.000740,-0.002929,0.000384,0.005576,-0.007282,0.007356,-0.000698,-0.000013,-0.001723
1996-06-30,-0.003317,-0.011897,-0.002149,-0.003016,0.004583,0.001125,-0.003372,0.001977,-0.004171,-0.003576,...,-0.000659,-0.000041,-0.000003,0.001566,0.007126,-0.005300,0.011308,-0.001577,-0.000133,0.004041
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-10-31,0.011078,0.015215,0.011320,0.008887,0.005543,0.009183,0.009071,0.014210,0.011965,0.006642,...,0.007074,0.007535,-0.003962,0.010589,0.006746,0.008454,0.021526,0.017047,0.010892,0.018063
2020-11-30,0.011290,0.013032,0.011743,0.007464,-0.001663,0.006515,0.010574,0.020050,0.011092,0.007106,...,0.003718,0.004774,-0.007977,0.004913,0.003969,0.002412,0.012874,0.017155,0.006666,0.009372
2020-12-31,0.007846,0.010475,0.007953,0.007326,0.005787,0.010187,0.008835,0.020950,0.009987,0.011315,...,0.002612,0.007981,-0.004294,0.007134,0.005717,0.003471,0.012905,0.013933,0.005089,0.009698
2021-01-31,0.005182,0.016473,0.004490,0.013151,-0.004481,0.004038,0.007315,0.022832,0.016108,0.005800,...,0.002057,0.002146,-0.000849,0.002782,-0.002359,0.003872,0.011692,0.009335,0.009755,0.004043
2021-02-28,0.009677,0.016939,0.009823,0.015446,-0.002191,0.004846,0.011333,0.023282,0.017954,0.003365,...,-0.003207,0.001879,-0.000932,0.001359,0.004007,-0.000301,0.002523,0.012365,0.010354,0.004726

In [8]:
#percent_change of prices
index_dates=["1996-01-31","2001-01-31","2006-01-31","2011-01-31","2016-01-31","2021-01-31"]
percent_change_df=pd.DataFrame(transposed_bayarea_price_df, index=index_dates)
percent_change_df

City,Alameda,Alamo,Albany,Antioch,Atherton,Belmont,Berkeley,Bethel Island,Brentwood,Brisbane,...,Sausalito,South San Francisco,Stanford,Sunnyvale,Sunol,Tiburon,Tomales,Union City,Walnut Creek,Woodacre
1996-01-31,205976.5,519268.0,215162.0,135345.5,768920.0,382693.0,230439.500,91301.0,177652.0,228102.0,...,418281.0,246054.0,889953.0,280969.50,225325.0,637431.0,361426.0,200579.0,176408.000000,351023.0
2001-01-31,337306.5,863522.0,367804.0,197536.0,1807420.0,733908.0,403278.000,139880.0,264694.0,420510.0,...,759383.0,430527.0,1450334.0,553477.50,444487.0,1146585.0,472742.0,356362.0,264660.666667,560458.0
2006-01-31,574908.5,1729667.0,644840.0,444517.5,2416121.0,1018108.0,671282.625,304730.0,559628.0,692181.0,...,1142332.0,729807.0,1915906.0,774637.75,636166.0,1679485.0,835331.0,616156.0,511609.333333,871281.0
2011-01-31,495473.5,1162808.0,561041.0,240277.0,2230351.0,853309.0,597957.625,182899.0,287088.0,543747.0,...,858190.0,531416.0,1798964.0,688901.75,626023.0,1422204.0,563624.0,436428.0,345966.000000,655162.0
2016-01-31,826009.5,1741298.0,904633.0,355551.5,4764834.0,1594607.0,1030164.875,324261.0,556908.0,836975.0,...,1246862.0,843410.0,2630354.0,1175769.00,1098056.0,2154495.0,743628.0,719288.0,557865.000000,825761.0
2021-01-31,1104088.0,2077690.0,1189380.0,514168.0,6557351.0,1921137.0,1480483.875,511506.0,737794.0,1116322.0,...,1517103.0,1142975.0,3296527.0,1624199.00,1266187.0,3093201.0,948524.0,1008695.0,721322.333333,972946.0

In [9]:
city_list=list(percent_change_df.columns)
twentyfive_years=[]
twenty_years=[]
fifteen_years=[]
ten_years=[]
five_years=[]
for city in city_list:
    twentyfive_years.append((percent_change_df[city][3]-percent_change_df[city][0])/percent_change_df[city][0])    
    twenty_years.append((percent_change_df[city][3]-percent_change_df[city][1])/percent_change_df[city][1])    
    fifteen_years.append((percent_change_df[city][3]-percent_change_df[city][2])/percent_change_df[city][2])        
    ten_years.append((percent_change_df[city][3]-percent_change_df[city][3])/percent_change_df[city][3])
    five_years.append((percent_change_df[city][3]-percent_change_df[city][4])/percent_change_df[city][4])

print (twentyfive_years,twenty_years,fifteen_years,ten_years,five_years)

[1.40548557723818, 1.2393215064282799, 1.6075282810161646, 0.7752862119538514, 1.9006281537741248, 1.2297481270888153, 1.594857326977363, 1.003252976418659, 0.6160133294305721, 1.3837888313123077, 1.3818484170369858, 1.678310710727396, 1.181052824651504, 1.900910355057013, 1.2918377823408624, 1.197417774955341, 1.68759038311042, 1.1830832117151997, 1.3555286889974234, 1.435297098343274, 0.5665503196801789, 0.5273144470920483, 1.1697577446453633, 1.695824134192065, 1.6846922815368923, 0.8140916585965923, 1.1485918598675506, 1.3569058281516801, 1.4933881130035624, 0.9142413327330031, 0.980106328910937, 0.929325069180707, 1.1287002566054538, 0.7344183036063352, 1.4101123216514317, 0.523416677243305, 1.3790254747118393, 1.1967906618096733, 1.0197648808012154, 1.426004465916595, 1.5333568612405974, 1.7369069923213576, 1.4514924388377186, 1.2157887453874539, 1.2231284868531676, 1.2058094272066027, 1.0681518110183246, 1.297428335496048, 1.0558372519388468, 1.0239611804435755, 1.6022085546275795, 1.1759730839275242, 0.6399154065254331, 0.9141403797026749, 1.3955195787623473, 0.6296965712201835, 0.9595213085234093, 1.0554821288993108, 1.2795850512138323, 1.2988113425494654, 1.4195036401685972, 1.3927003139669298, 0.7945122462869556, 1.36869416373508, 1.2705885295872896, 0.6285108527432288, 1.3800625737428909, 1.9948444656695683, 0.9395231279095259, 1.2696320901180633, 1.2816664655969758, 1.403384000475566, 0.8282048079367983, 1.2774301713854286, 0.9066054788685476, 1.0598919187527176, 1.100944113547079, 1.31990113503486, 0.6506880192344847, 0.20671865554163327, 0.8933271283094605, 1.207943037501309, 1.5195956958544987, 1.5267858302336583, 1.0517068669148253, 1.1597535500337324, 1.0214146140301792, 1.451873779894259, 1.7783113280816598, 1.231149724440763, 0.559445086961093, 1.1758409404773182, 0.9611695614711351, 0.8664361024776154] [0.4689118057315824, 0.3465875797026596, 0.5253803656295201, 0.2163706868621416, 0.23399707870887784, 0.16269205404492115, 0.48274298374818364, 0.3075421790105805, 0.08460335330608174, 0.2930655632446315, 0.26158661179524645, 0.3446210668857647, 0.3533939844603618, 0.6577974244161282, 0.44608197333997757, 0.22388880053436813, 0.3772795410742445, 0.2531358515478463, 0.3676387472037043, 0.33638411031172777, 0.19242500634706086, 0.08207727448582025, 0.34524575196039115, 0.3998056553281983, 0.5236918991728966, 0.17662237349709498, 0.317337021982172, 0.2568938797810452, 0.3718267816157802, 0.05730521499092288, 0.1290319964133814, 0.16559027744432386, 0.20993057634624834, 0.12736736742389482, 0.4694017726777305, 0.04840819845652025, 0.24817251080972452, 0.24363424532164446, 0.2527063250683025, 0.256165389938147, 0.2673623258619846, 0.5745040879238708, 0.23335343420652263, 0.20250572612238257, 0.23471124374337052, 0.20386045763385507, 0.1306232098825974, 0.4483949836848906, 0.12561950842531458, 0.09009168096757053, 0.33041153369150544, 0.23600988878044218, 0.03772750881303113, 0.16605903218154716, 0.45923764012728757, 0.19839374566922044, 0.30386919620569147, 0.17674721340818486, 0.21621885207930086, 0.5254056245951172, 0.3237035932126861, 0.42704428829716407, 0.12478962131837307, 0.12015152521079214, 0.17368492218481024, 0.18347675524802853, 0.6647472007789137, 0.6479279736620107, 0.19507078848632303, 0.2785115917498469, 0.18007576240775816, 0.2179200361970152, 0.27735129845033724, 0.22861159960386737, 0.2202796632483531, 0.26333153014499155, 0.05370856181307113, 0.22769501162008923, 0.4404345993537208, -0.1364064663524355, 0.16812161794760822, 0.4319119296244126, 0.28429078965936105, 0.26366719983374093, 0.13011484323457334, 0.2343383806358254, 0.24037911267335663, 0.2446788713181656, 0.4084168940823916, 0.24038252724394615, 0.19224439546306443, 0.22467603167565564, 0.30720595681010393, 0.16897608741422193] [-0.13816981310939044, -0.32772724460835523, -0.12995316667700516, -0.4594656003419438, -0.07688770554123737, -0.16186789613675562, -0.10923119006692598, -0.39979982279394877, -0.48700207995311173, -0.21444390990217876, -0.11773859817587405, -0.054510124359579595, -0.23905780165570142, -0.2198984465837407, -0.336382424656477, -0.21463666334106765, 0.052576920787954534, -0.27895522838351533, -0.3031984898094131, -0.295517660287946, -0.3287897604560212, -0.39609736734778445, -0.23476807414740528, -0.13036666810652264, -0.22988660459472798, -0.37895316903143716, -0.18846519183381286, -0.12947661024693943, -0.1640962034435827, -0.3471839204004545, -0.23567176904706758, -0.3857774898818207, -0.20893117913103598, 0.13228765361552128, -0.2354437314552363, -0.2697758850773216, -0.24224134900041489, -0.1373202339347376, -0.2929499877557651, -0.040807449639631635, -0.05968295224582693, -0.26868006163136354, -0.08686345394356886, -0.18045825332822665, -0.1815270499013209, -0.19335397238298593, -0.23068067707958595, -0.20831952910473395, -0.2510235507499518, -0.23665520032375556, -0.025374852047646067, -0.2890220923059338, -0.327141067861268, -0.30436813293553006, -0.2167624624922099, -0.44114288426658294, -0.3055483607921615, -0.29172588987849296, -0.11346850641771712, -0.296019389557573, -0.36318552696142603, -0.15982846935111794, -0.21609403254972875, -0.1033883677164095, -0.17557615609445199, -0.45222354955480865, -0.22468787652390967, 0.0703733623755386, -0.24254806965945833, -0.24277247759468054, -0.1624278258747253, -0.1702039743553556, -0.18942393651948955, -0.17065240312884625, -0.35860800297858164, -0.356232540713261, -0.2958728722766043, -0.18341573539634426, -0.3449920779596913, -0.34178991491077865, -0.2756386184192904, -0.2652174107838457, -0.11218347976321921, -0.01835963963963964, -0.24873854536159365, -0.2718403632741259, -0.06103744129409271, -0.11067883020160069, -0.01594395173586768, -0.15319041253717658, -0.32526866595397513, -0.2916923636221996, -0.32376917804470595, -0.24804741524261403] [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] [-0.40016004658542065, -0.33221769048146843, -0.37981369240343876, -0.3242132293071468, -0.5319142282816148, -0.4648781800155148, -0.41955153052563554, -0.4359512861552885, -0.4844965416190825, -0.3503426028256519, -0.4695802666994735, -0.35556495431927376, -0.32754564613360376, -0.19239389306357488, -0.4021533952930209, -0.2554378534353178, -0.3951437634123612, -0.39439109061423067, -0.3213309769518747, -0.2874895600364542, -0.2489786542108274, -0.4628760310058272, -0.3569734679926843, -0.28501662663397065, -0.3652704623359251, -0.25108052037861434, -0.2885926369307149, -0.4309255510973718, -0.40005820974645445, -0.3681996305669445, -0.305138242699395, -0.38492902739746854, -0.38794572593448573, 0.020260921004383606, -0.3153244831822215, -0.3262459975676075, -0.2904301664353236, -0.24874858263628288, -0.3779627550537926, -0.34798448894786105, -0.32022979355609577, -0.44541093020648304, -0.4792746767522276, -0.3442496962747587, -0.4105607069305679, -0.35696179177807996, -0.26158696478971916, -0.35947574843160307, -0.3218589598418014, -0.32857364627756613, -0.4154845917837395, -0.41518228111679073, -0.2887094892766735, -0.28061979963432226, -0.4216365880116433, -0.42532543112349297, -0.2804087047478123, -0.34216905828576627, -0.39147670057111567, -0.3304173793750163, -0.3856663080593105, -0.33108090394295303, -0.29511592789313124, -0.5157016641039802, -0.4369525914680345, -0.35318264939691685, 0.09781757921900033, -0.47221384055015225, -0.315088667128726, -0.38600868420510004, -0.48330163186183056, -0.3934778954345924, -0.24150832002339342, -0.3344103764709557, -0.36319512632580536, -0.3813414820701672, -0.27629393417540277, -0.4576527367951833, -0.21338274370797752, -0.26028468521349535, -0.2638815574223293, -0.32158044429082794, -0.37810400835529007, -0.3773649508872837, -0.3117201422450921, -0.3699197306173747, -0.31607532674309236, -0.4140841015539617, -0.4298806253961547, -0.3398898581802232, -0.2420618911606341, -0.3932499916584178, -0.379839208410637, -0.20659609741801804]

In [10]:
#five years
five_years_array=np.array(five_years)
round_to_thousands_5=np.around(five_years_array,4)
five_years_rounded=list(round_to_thousands_5)
#ten years
ten_years_array=np.array(ten_years)
round_to_thousands_10=np.around(ten_years_array,4)
ten_years_rounded=list(round_to_thousands_10)
#fifteen years
fifteen_years_array=np.array(fifteen_years)
round_to_thousands_15=np.around(fifteen_years_array,4)
fifteen_years_rounded=list(round_to_thousands_15)

#twenty years
twenty_years_array=np.array(twenty_years)
round_to_thousands_20=np.around(twenty_years_array,4)
twenty_years_rounded=list(round_to_thousands_20)
#twenty five  years
twentyfive_years_array=np.array(twentyfive_years)
round_to_thousands_25=np.around(twentyfive_years_array,4)
twentyfive_years_rounded=list(round_to_thousands_25)

In [11]:
#perchange of 5, 10, 15 years in prices
index_names=["25_years","20_years","15_years","10_years","5_years"]
growth_df=pd.DataFrame(index=index_names)
for i in range(len(city_list)):
    growth_df[city_list[i]]=[twentyfive_years_rounded[i] , twenty_years_rounded[i] , fifteen_years_rounded[i] , ten_years_rounded[i] , five_years_rounded[i]]
#save as csv
growth_df=growth_df.transpose()
growth_df

              25_years  20_years  15_years  10_years  5_years
Alameda         1.4055    0.4689   -0.1382       0.0  -0.4002
Alamo           1.2393    0.3466   -0.3277       0.0  -0.3322
Albany          1.6075    0.5254   -0.1300       0.0  -0.3798
Antioch         0.7753    0.2164   -0.4595       0.0  -0.3242
Atherton        1.9006    0.2340   -0.0769       0.0  -0.5319
...                ...       ...       ...       ...      ...
Tiburon         1.2311    0.2404   -0.1532       0.0  -0.3399
Tomales         0.5594    0.1922   -0.3253       0.0  -0.2421
Union City      1.1758    0.2247   -0.2917       0.0  -0.3932
Walnut Creek    0.9612    0.3072   -0.3238       0.0  -0.3798
Woodacre        0.8664    0.1690   -0.2480       0.0  -0.2066

[94 rows x 5 columns]